matrix:
  include:
    - os: "linux"
      env: NODE_VERSION="6.2.0"
    - os: "linux"
      env: NODE_VERSION="5.11.1"

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION

install: echo "install"

script:
  - npm install
  - npm run build
